media:
  - name: site-images
    label: Site Images
    input: src/assets/images
    output: src/assets/images
    categories: [image]
    extensions: [jpg, jpeg, png, webp, avif]
  - name: public-images
    label: Public Images
    input: public/images
    output: /images
    categories: [image]
    extensions: [jpg, jpeg, png, webp, avif]
  - name: portfolio-images
    label: Portfolio Images
    input: src/assets/images
    output: src/assets/images
    categories: [image]
    extensions: [jpg, jpeg, png, webp, avif]
  - name: testimonial-images
    label: Testimonial Images
    input: src/assets/images
    output: src/assets/images
    categories: [image]
    extensions: [jpg, jpeg, png, webp, avif]

content:
  - name: home-page
    label: Home Page
    type: file
    path: src/data/pages/home.json
    fields:
      - name: hero
        label: Hero
        type: object
        fields:
          - name: heading
            label: Heading
            type: string
            required: true
          - name: subtitle
            label: Subtitle
            type: string
            required: true
          - name: ctaText
            label: CTA Text
            type: string
            required: true
          - name: image
            label: Hero Image
            type: image
            media: site-images
      - name: whatIDo
        label: What I Do
        type: object
        fields:
          - name: heading
            label: Heading
            type: string
            required: true
          - name: tagline
            label: Tagline
            type: string
            required: true
          - name: missionStatement
            label: Mission Statement
            type: text
            required: true
          - name: items
            label: Items
            type: object
            list: true
            fields:
              - name: largeText
                label: Large Text
                type: string
                required: true
              - name: description
                label: Description
                type: string
                required: true
      - name: about
        label: About
        type: object
        fields:
          - name: subheading
            label: Subheading
            type: string
            required: true
          - name: heading
            label: Heading
            type: string
            required: true
          - name: body
            label: Body
            type: text
            required: true
          - name: signoff
            label: Signoff
            type: string
            required: true
          - name: image
            label: Profile Image
            type: image
            media: site-images
      - name: contact
        label: Contact
        type: object
        fields:
          - name: heading
            label: Heading
            type: string
            required: true
          - name: description
            label: Description
            type: text
            required: true
          - name: image
            label: Contact Image
            type: image
            media: site-images
      - name: testimonialQuote
        label: Testimonial Quote
        type: object
        fields:
          - name: quoteText
            label: Quote Text
            type: string
            required: true
          - name: attribution
            label: Attribution
            type: string
            required: true

  - name: about-page
    label: About Page
    type: file
    path: src/data/pages/about.json
    fields:
      - name: pageTitle
        label: Page Title
        type: string
        required: true
      - name: pageDescription
        label: Page Description
        type: string
        required: true
      - name: sections
        label: Sections
        type: object
        list: true
        fields:
          - name: heading
            label: Heading
            type: string
            required: true
          - name: paragraph1
            label: Paragraph 1
            type: text
            required: true
          - name: paragraph2
            label: Paragraph 2
            type: text
            required: true
          - name: image
            label: Section Image
            type: image
            media: site-images
          - name: imageAlt
            label: Image Alt Text
            type: string
            required: true

  - name: case-studies-page
    label: Case Studies Page
    type: file
    path: src/data/pages/case-studies.json
    fields:
      - name: pageTitle
        label: Page Title
        type: string
        required: true
      - name: pageDescription
        label: Page Description
        type: string
        required: true
      - name: heading
        label: Heading
        type: string
        required: true
  - name: services-page
    label: Services Page
    type: file
    path: src/data/pages/services.json
    fields:
      - name: heading
        label: Heading
        type: string
        required: true
      - name: ctaText
        label: CTA Text
        type: string
        required: true
  - name: portfolios
    label: Case Studies
    type: collection
    path: src/data/portfolios
    format: yaml-frontmatter
    subfolders: true
    filename: index
    view:
      fields: [title, location, date, order]
      primary: title
      sort: [order, date]
      search: [title, location, description]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: heroImage
        label: Hero Image
        type: image
        media: portfolio-images
      - name: clients
        label: Clients
        type: string
        list: true
      - name: location
        label: Location
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: order
        label: Order
        type: number
        required: true
      - name: draft
        label: Draft
        type: boolean
        default: false

  - name: testimonials
    label: Testimonials
    type: collection
    path: src/data/testimonials
    format: yaml-frontmatter
    subfolders: true
    filename: index
    view:
      fields: [title, order]
      primary: title
      sort: [order]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: testimonial
        label: Testimonial
        type: text
        required: true
      - name: image
        label: Image
        type: image
        media: testimonial-images
      - name: order
        label: Order
        type: number
        required: true
      - name: draft
        label: Draft
        type: boolean
        default: false

  - name: services
    label: Services
    type: collection
    path: src/data/services
    format: yaml-frontmatter
    subfolders: true
    filename: index
    view:
      fields: [name, price, order]
      primary: name
      sort: [order]
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: icon
        label: Icon
        type: select
        required: true
        options:
          values:
            - { value: "tabler:message", label: "Message" }
            - { value: "tabler:pencil", label: "Pencil" }
            - { value: "tabler:notebook", label: "Notebook" }
            - { value: "tabler:shovel", label: "Shovel" }
            - { value: "tabler:shopping-cart", label: "Shopping Cart" }
            - { value: "tabler:plant-2", label: "Plant" }
            - { value: "tabler:bulb", label: "Bulb" }
            - { value: "tabler:target", label: "Target" }
            - { value: "tabler:category", label: "Category" }
      - name: price
        label: Price
        type: string
        required: true
      - name: features
        label: Features
        type: string
        list: true
      - name: order
        label: Order
        type: number
        required: true
      - name: draft
        label: Draft
        type: boolean
        default: false

  - name: other-pages
    label: Other Pages
    type: collection
    path: src/data/otherPages
    format: yaml-frontmatter
    view:
      fields: [title]
      primary: title
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: draft
        label: Draft
        type: boolean
        default: false
